#ifndef PARAM_H
#define PARAM_H

#define TICK_PER_SEC 100
#define MAX_HP 2000

#define GAME_HEIGHT 960
#define GAME_WIDTH 540


#define RUNE_COUNT_X 6
#define RUNE_COUNT_Y 5
#define RUNE_AREA_HEIGHT 450
#define RUNE_AREA_WIDTH 540
#define RUNE_AREA_X 0
#define RUNE_AREA_Y (GAME_HEIGHT - RUNE_AREA_HEIGHT)

#define RUNE_HEIGHT 90
#define RUNE_WIDTH 90

#define RUNE_GRAVITY_ACCELERATION 3

#define DUMMY_OPACITY 0.7
#define DUMMY_INACTIVE_OPACITY 0
#define RUNE_OPACITY 0.3

//300ms
#define LINKING_CD 300

#define BOARD_Z_VALUE -100



// debug settings
#define DEBUG_REMOVE 1
#define DEBUG_MOUSE 0

#endif // PARAM_H
